<div class="container">
	<?php
		$this->title = "delete Car details";
		$this->headTitle($this->title);
	?>
	<p>Are you sure to delete the record?
	<?php echo $this->escape($this->cars['id']); ?> 
	<?php echo $this->escape($this->cars['brandid']); ?>
	</p>
	<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
		<div>
		<input type="hidden" name="id" value="<?php echo $this->cars['id']; ?>" />
		<input type="submit" name="del" value="Yes"/>
		<input type="submit" name="del" value="No"/>
		</div>
	</form>
</div>